
package grocery_shop;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.table.DefaultTableModel;

public class Order_History extends javax.swing.JFrame {

    Admin admin = new Admin();
    Data data = Data.getInstance();
    DefaultComboBoxModel model = new DefaultComboBoxModel();
    DefaultListModel listModel = new DefaultListModel();;
    DefaultTableModel tableModel = new DefaultTableModel();
    String[] columnNames = { "ProductID", "Product Name", "Quantity", "Price"};
    
    
    public Order_History() {
        
        updateComboBox();
        initComponents();
    }

    private void updateComboBox() {
        model.removeAllElements();

        
        for (int i = 0; i < admin.getShops().size(); i++) {
            model.addElement(admin.getShops().get(i).getId());
        }
        
        if (shopCombo != null) {
            shopCombo.setModel(model);
      }
//        int i = 0;
//        while (i < data.getCat().size()){             
//            model.addElement(data.getCat().get(i).getCategoryname());    
//            i++;           
//        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        shopCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        detailsTable = new javax.swing.JTable();
        back_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel1.setText("View History");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 36, -1, -1));

        shopCombo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        shopCombo.setModel(model);
        shopCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopComboActionPerformed(evt);
            }
        });
        getContentPane().add(shopCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 33, 119, 41));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setText("Shop ID");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 38, -1, -1));

        orderList.setBackground(new java.awt.Color(248, 248, 248));
        orderList.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        orderList.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        orderList.setModel(listModel);
        orderList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                orderListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(orderList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 154, 164, 355));

        detailsTable.setBackground(new java.awt.Color(248, 248, 248));
        detailsTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        detailsTable.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        detailsTable.setModel(tableModel);
        jScrollPane2.setViewportView(detailsTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 154, 410, 355));

        back_btn.setBackground(new java.awt.Color(248, 248, 248));
        back_btn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        back_btn.setText("< Back");
        back_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_btnMouseClicked(evt);
            }
        });
        getContentPane().add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 577, 110, 38));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel3.setText("History");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 119, -1, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel4.setText("Order ID");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 119, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/nadafaid/Desktop/51125402135_1f84a49586_b.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, -1, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shopComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopComboActionPerformed
        orderList.removeAll();
        listModel = new DefaultListModel();
        for(int i = 0; i < data.getOrder().size(); i++){
            if (data.getOrder().get(i).getShop_id() == (int) shopCombo.getSelectedItem()){
                listModel.addElement(data.getOrder().get(i).getId());
            }                        
        }
        if (orderList != null) {
            orderList.setModel(listModel);
        }
    }//GEN-LAST:event_shopComboActionPerformed

    private void orderListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_orderListValueChanged
        detailsTable.removeAll();
        tableModel = new DefaultTableModel(columnNames,0);
        for(int i = 0; i < data.getOrder_details().size(); i++){
            Object arr = orderList.getSelectedValue();
           
            if(arr != null && data.getOrder_details().get(i).getOrder_id() == (int)arr){
                
                Order_Details od = data.getOrder_details().get(i);
                Object[] obj = new Object[] {od.getProduct_id(),od.getProd_name(),od.getQuantity(),od.getProd_price()};           
                 tableModel.addRow(obj);
                    
            }
        }
        if (detailsTable != null) {
            detailsTable.setModel(tableModel);
        }
        
    }//GEN-LAST:event_orderListValueChanged

    private void back_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseClicked
        this.setVisible(false);
        Admin_Powers AD = new Admin_Powers();
        AD.setVisible(true);
        AD.setLocationRelativeTo(null);
    }//GEN-LAST:event_back_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order_History().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JTable detailsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> orderList;
    private javax.swing.JComboBox<String> shopCombo;
    // End of variables declaration//GEN-END:variables
}
